/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.net.URL;
import java.net.MalformedURLException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws MalformedURLException {
        //System.out.println(new App().getGreeting());
        LRUCache<String, String> cache = new LRUCache<>(5);
        String url = cache.filteredURL("https://www.example.com/page");
        String url2 = cache.filteredURL("www.example.com/page");
        String url3 = cache.filteredURL("example.com/page");
        String url4 = cache.filteredURL("mail.google.com");
        String url5 = cache.filteredURL("mail.google.com/mail/u/1/#inbox");
        String url6 = cache.filteredURL("harper.blackboard.com");
        String url7 = cache.filteredURL("http://harper.blackboard.com");

        cache.put(url, url);
        System.out.println("Insertion 1: ");
        System.out.println(cache);

        cache.put(url2, url2);
        System.out.println("Insertion 2: ");
        System.out.println(cache);

        cache.put(url3, url3);
        System.out.println("Insertion 3: ");
        System.out.println(cache);

        cache.put(url4, url4);
        System.out.println("Insertion 4: ");
        System.out.println(cache);

        cache.put(url5, url5);
        System.out.println("Insertion 5: ");
        System.out.println(cache);

        cache.put(url6, url6);
        System.out.println("Insertion 6: ");
        System.out.println(cache);

        cache.put(url7, url7);
        System.out.println("Insertion 7: ");
        System.out.println(cache);
    }
}
